(require 'ert)
(require 'gazr)

(ert-deftest extract-words-first-letters ()
  (should (equal (gazr--extract-words-first-letters "foobar") "f"))
  (should (equal (gazr--extract-words-first-letters "foo-bar") "fb"))
  (should (equal (gazr--extract-words-first-letters "foo-bar-lol") "fbl")))
  (should (equal (gazr--extract-words-first-letters "foo--bar") "fb"))
  (should (equal (gazr--extract-words-first-letters "-") nil))
  (should (equal (gazr--extract-words-first-letters "") nil))

(ert-deftest parse-makefile-targets ()
  (should (equal (gazr--parse-makefile-targets ".PHONY: foo\nfoo:\n") (list "foo")))
  (should (equal (gazr--parse-makefile-targets "") (list)))
  (should (equal (gazr--parse-makefile-targets ".PHONY: foo foo\n") (list "foo")))
  (should (equal (gazr--parse-makefile-targets ".PHONY: foo") (list "foo")))
  (should (equal (gazr--parse-makefile-targets ".PHONY: foo bar lol\n") (list "foo" "bar" "lol"))))
